
DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;

DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,    --글번호
	GROUPNO NUMBER NOT NULL,		--그룹번호
	GROUPSEQ NUMBER NOT NULL,		--그룹순서
	TITLETAB NUMBER NOT NULL,		--제목공백
	TITLE VARCHAR2(1000) NOT NULL,		--제목
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(500) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;

--글작성1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '답변형 게시판', '사실 쉬운 방법 있지만 오라클에서 쓰려고','강사가',SYSDATE);

--글작성2
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '두번째글','두번쨰 내용','나',SYSDATE);

--2번글에 답변
--UPDATE: 부모의 글과 같은 그룹이면서, 부모의 순서 다음순서에 있는 글들을 찾아서 순서+1
	
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 2)
   AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 2);


--INSERT: 부모의 글과 같은 그룹, 부모의 순서+1, 부모의 제목공백+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, 
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 2),
	(SELECT GROUPSEQ + 1 FROM ANSWERBOARD WHERE BOARDNO = 2),
	(SELECT TITLETAB + 1 FROM ANSWERBOARD WHERE BOARDNO = 2),
	' RE: 두번째글','내용','강사',SYSDATE);
--3번글(2번의 답변글) 에다가 답변

--UPDATE랑 INSERT 가 묶여서 답변작업 하나가 됨(트랜잭션)

UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 3)
	AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 3);
	
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 3),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 3) + 1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 3) + 1,
	'  RE:RE:두번째글','두번재 답변','빵',SYSDATE
	
);

















